import {
  AgentDevice,
  AlertEvent,
  AuditLog,
  Client,
  Contract,
  InventoryItem,
  InventoryMovement,
  Invoice,
  MeterReading,
  OracleSyncLog,
  Printer,
  RouteStop,
  ServiceOrder,
  Technician,
  Ticket,
  User,
} from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'Carlos Albuquerque',
    email: 'carlos@santaprint.com.br',
    role: 'ADMIN',
    companyId: 'comp-1',
  },
  {
    id: 'usr-2',
    name: 'Mariana Duarte',
    email: 'mariana.gestao@santaprint.com.br',
    role: 'GESTOR',
    companyId: 'comp-1',
  },
  {
    id: 'usr-3',
    name: 'Rodrigo Santos',
    email: 'rodrigo.tec@santaprint.com.br',
    role: 'TECNICO',
    companyId: 'comp-1',
  },
  {
    id: 'usr-4',
    name: 'Juliana Mendes',
    email: 'juliana.fat@santaprint.com.br',
    role: 'FATURAMENTO',
    companyId: 'comp-1',
  },
  {
    id: 'usr-5',
    name: 'Dr. Fernando Prado',
    email: 'suprimentos@hospitalsantacatarina.com.br',
    role: 'CLIENTE',
    clientId: 'cli-1',
    companyId: 'comp-1',
  },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli-1',
    corporateName: 'Hospital Santa Catarina S/A',
    tradeName: 'Hospital Santa Catarina',
    cnpj: '45.123.456/0001-89',
    stateRegistration: '109.876.543.210',
    phone: '(11) 3286-9000',
    email: 'ti@hospitalsantacatarina.com.br',
    address: 'Av. Paulista, 200',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01310-000',
    contactPerson: 'Dr. Fernando Prado (Diretoria TI)',
    status: 'ATIVO',
    notes: 'Ambiente hospitalar com SLA crítico de 4 horas para pronto atendimento.',
    createdAt: '2024-02-15T08:00:00Z',
    branches: [
      {
        id: 'br-1-1',
        clientId: 'cli-1',
        name: 'Sede Bela Vista',
        cnpj: '45.123.456/0001-89',
        address: 'Av. Paulista, 200',
        city: 'São Paulo',
        state: 'SP',
        zipCode: '01310-000',
        phone: '(11) 3286-9000',
        contactPerson: 'Juliano Prado',
        latitude: -23.5658,
        longitude: -46.6515,
      },
      {
        id: 'br-1-2',
        clientId: 'cli-1',
        name: 'Unidade Ambulatório Santos',
        cnpj: '45.123.456/0002-60',
        address: 'Av. Ana Costa, 150',
        city: 'Santos',
        state: 'SP',
        zipCode: '11060-000',
        phone: '(13) 3222-1000',
        contactPerson: 'Renata Lins',
        latitude: -23.9554,
        longitude: -46.3312,
      },
    ],
    departments: [
      { id: 'dep-1-1', clientId: 'cli-1', name: 'Pronto Atendimento / Triagem' },
      { id: 'dep-1-2', clientId: 'cli-1', name: 'Centro Cirúrgico' },
      { id: 'dep-1-3', clientId: 'cli-1', name: 'Farmácia Central' },
      { id: 'dep-1-4', clientId: 'cli-1', name: 'Administrativo & Financeiro' },
    ],
  },
  {
    id: 'cli-2',
    corporateName: 'Alfa Engenharia e Construções Ltda',
    tradeName: 'Construtora Alfa',
    cnpj: '61.987.654/0001-12',
    stateRegistration: '112.334.455.667',
    phone: '(11) 4589-3300',
    email: 'projetos@alfaengenharia.com.br',
    address: 'Rua Funchal, 418 - 12º andar',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '04551-060',
    contactPerson: 'Engª Sofia Morais',
    status: 'ATIVO',
    notes: 'Grande volume de impressão A3 para plantas arquitetônicas e memoriais de obra.',
    createdAt: '2024-05-10T09:30:00Z',
    branches: [
      {
        id: 'br-2-1',
        clientId: 'cli-2',
        name: 'Matriz Vila Olímpia',
        cnpj: '61.987.654/0001-12',
        address: 'Rua Funchal, 418',
        city: 'São Paulo',
        state: 'SP',
        zipCode: '04551-060',
        phone: '(11) 4589-3300',
        contactPerson: 'Sofia Morais',
        latitude: -23.5934,
        longitude: -46.6853,
      },
    ],
    departments: [
      { id: 'dep-2-1', clientId: 'cli-2', name: 'Engenharia & Projetos CAD' },
      { id: 'dep-2-2', clientId: 'cli-2', name: 'Jurídico & Licitações' },
      { id: 'dep-2-3', clientId: 'cli-2', name: 'Compras & Suprimentos' },
    ],
  },
  {
    id: 'cli-3',
    corporateName: 'Colégio e Faculdade Sigma Brasil Ltda',
    tradeName: 'Grupo Educacional Sigma',
    cnpj: '18.445.889/0001-77',
    stateRegistration: '223.445.667.889',
    phone: '(19) 3744-8800',
    email: 'operacoes@sigmaeduca.com.br',
    address: 'Av. Barão de Itapura, 1500',
    city: 'Campinas',
    state: 'SP',
    zipCode: '13020-432',
    contactPerson: 'Prof. Márcio Caldeira',
    status: 'ATIVO',
    notes: 'Picos sazonais de provas escolares e apostilas bimestrais.',
    createdAt: '2024-08-01T11:00:00Z',
    branches: [
      {
        id: 'br-3-1',
        clientId: 'cli-3',
        name: 'Campus Barão - Campinas',
        cnpj: '18.445.889/0001-77',
        address: 'Av. Barão de Itapura, 1500',
        city: 'Campinas',
        state: 'SP',
        zipCode: '13020-432',
        phone: '(19) 3744-8800',
        contactPerson: 'Prof. Márcio Caldeira',
        latitude: -22.8945,
        longitude: -47.0583,
      },
    ],
    departments: [
      { id: 'dep-3-1', clientId: 'cli-3', name: 'Gráfica Interna / Reprografia' },
      { id: 'dep-3-2', clientId: 'cli-3', name: 'Secretaria Acadêmica' },
      { id: 'dep-3-3', clientId: 'cli-3', name: 'Coordenação Pedagógica' },
    ],
  },
];

export const INITIAL_PRINTERS: Printer[] = [
  {
    id: 'prt-1',
    code: 'PRT-HSC-001',
    serialNumber: 'CNB1N8G202',
    assetTag: 'PAT-00892',
    manufacturer: 'HP',
    model: 'LaserJet Enterprise MFP M528dn',
    ipAddress: '192.168.10.45',
    macAddress: '3C:D9:2B:44:88:1A',
    hostname: 'HP-TRIAGEM-01',
    location: 'Sede Bela Vista - Térreo Triagem',
    clientId: 'cli-1',
    branchId: 'br-1-1',
    departmentId: 'dep-1-1',
    contractId: 'ctr-1',
    type: 'MULTIFUNCIONAL',
    technology: 'LASER',
    isColor: false,
    maxPaperSize: 'A4',
    connectionType: 'REDE',
    status: 'ATIVA',
    isMonitored: true,
    installedAt: '2024-03-01T10:00:00Z',
    lastCommunication: '2026-09-18T10:15:00Z',
    snmpCommunity: 'public',
    firmwareVersion: 'FS4-25.04.01',
    supplies: [
      {
        type: 'TONER_BLACK',
        label: 'Toner Preto CF289A',
        percent: 68,
        status: 'NORMAL',
        estimatedPagesRemaining: 3400,
        model: 'CF289A',
        colorCode: '#1e293b',
      },
      {
        type: 'DRUM',
        label: 'Unidade de Imagem / Cilindro',
        percent: 82,
        status: 'NORMAL',
        estimatedPagesRemaining: 18000,
        model: 'HP-M528-DRUM',
        colorCode: '#64748b',
      },
      {
        type: 'FUSER',
        label: 'Fusor 110V',
        percent: 91,
        status: 'NORMAL',
        estimatedPagesRemaining: 65000,
        model: 'RM2-2005-000',
        colorCode: '#f97316',
      },
    ],
    lastCounters: {
      total: 148920,
      mono: 148920,
      color: 0,
      prints: 112400,
      copies: 36520,
      scans: 41200,
      readAt: '2026-09-18T10:15:00Z',
    },
  },
  {
    id: 'prt-2',
    code: 'PRT-HSC-002',
    serialNumber: 'QSK2A99120',
    assetTag: 'PAT-00893',
    manufacturer: 'Kyocera',
    model: 'ECOSYS M3655idn',
    ipAddress: '192.168.10.46',
    macAddress: '00:17:C8:11:5F:E2',
    hostname: 'KYO-FARMACIA-01',
    location: 'Sede Bela Vista - 1º Andar Farmácia',
    clientId: 'cli-1',
    branchId: 'br-1-1',
    departmentId: 'dep-1-3',
    contractId: 'ctr-1',
    type: 'MULTIFUNCIONAL',
    technology: 'LASER',
    isColor: false,
    maxPaperSize: 'A4',
    connectionType: 'REDE',
    status: 'ATIVA',
    isMonitored: true,
    installedAt: '2024-03-01T11:00:00Z',
    lastCommunication: '2026-09-18T10:20:00Z',
    snmpCommunity: 'public',
    firmwareVersion: '2VG_2000.003.001',
    supplies: [
      {
        type: 'TONER_BLACK',
        label: 'Toner TK-3182',
        percent: 8,
        status: 'CRÍTICO',
        estimatedPagesRemaining: 420,
        model: 'TK-3182',
        colorCode: '#1e293b',
      },
      {
        type: 'DRUM',
        label: 'Cilindro DK-3192',
        percent: 74,
        status: 'NORMAL',
        estimatedPagesRemaining: 74000,
        model: 'DK-3192',
        colorCode: '#64748b',
      },
    ],
    lastCounters: {
      total: 89450,
      mono: 89450,
      color: 0,
      prints: 71200,
      copies: 18250,
      scans: 19400,
      readAt: '2026-09-18T10:20:00Z',
    },
  },
  {
    id: 'prt-3',
    code: 'PRT-ALF-001',
    serialNumber: '7529486241',
    assetTag: 'PAT-01044',
    manufacturer: 'Ricoh',
    model: 'MP C3004ex A3 Color',
    ipAddress: '10.0.50.88',
    macAddress: '00:26:73:9A:C3:01',
    hostname: 'RICOH-PROJETOS-CAD',
    location: 'Matriz Funchal - Sala de Projetos CAD',
    clientId: 'cli-2',
    branchId: 'br-2-1',
    departmentId: 'dep-2-1',
    contractId: 'ctr-2',
    type: 'MULTIFUNCIONAL',
    technology: 'LASER',
    isColor: true,
    maxPaperSize: 'A3',
    connectionType: 'REDE',
    status: 'ATIVA',
    isMonitored: true,
    installedAt: '2024-06-01T09:00:00Z',
    lastCommunication: '2026-09-18T10:18:00Z',
    snmpCommunity: 'public',
    firmwareVersion: 'v2.19',
    supplies: [
      {
        type: 'TONER_BLACK',
        label: 'Toner Preto MP C3503',
        percent: 45,
        status: 'NORMAL',
        estimatedPagesRemaining: 13500,
        model: 'MP C3503 Black',
        colorCode: '#1e293b',
      },
      {
        type: 'TONER_CYAN',
        label: 'Toner Ciano MP C3503',
        percent: 32,
        status: 'NORMAL',
        estimatedPagesRemaining: 5700,
        model: 'MP C3503 Cyan',
        colorCode: '#0ea5e9',
      },
      {
        type: 'TONER_MAGENTA',
        label: 'Toner Magenta MP C3503',
        percent: 14,
        status: 'BAIXO',
        estimatedPagesRemaining: 2100,
        model: 'MP C3503 Magenta',
        colorCode: '#ec4899',
      },
      {
        type: 'TONER_YELLOW',
        label: 'Toner Amarelo MP C3503',
        percent: 54,
        status: 'NORMAL',
        estimatedPagesRemaining: 9800,
        model: 'MP C3503 Yellow',
        colorCode: '#eab308',
      },
      {
        type: 'WASTE_BOX',
        label: 'Garrafa Resíduo Toner',
        percent: 85,
        status: 'NORMAL',
        estimatedPagesRemaining: 8000,
        model: 'Waste Bottle MP3503',
        colorCode: '#78716c',
      },
    ],
    lastCounters: {
      total: 210340,
      mono: 132100,
      color: 78240,
      prints: 175000,
      copies: 35340,
      scans: 48900,
      readAt: '2026-09-18T10:18:00Z',
    },
  },
  {
    id: 'prt-4',
    code: 'PRT-SIG-001',
    serialNumber: '7463554101',
    assetTag: 'PAT-01201',
    manufacturer: 'Lexmark',
    model: 'XC4140 Color Multifunction',
    ipAddress: '172.16.2.14',
    macAddress: '00:04:00:88:DF:99',
    hostname: 'LEX-REPROGRAFIA',
    location: 'Campus Barão - Gráfica Interna',
    clientId: 'cli-3',
    branchId: 'br-3-1',
    departmentId: 'dep-3-1',
    contractId: 'ctr-3',
    type: 'MULTIFUNCIONAL',
    technology: 'LASER',
    isColor: true,
    maxPaperSize: 'A4',
    connectionType: 'REDE',
    status: 'ATIVA',
    isMonitored: true,
    installedAt: '2024-08-15T09:00:00Z',
    lastCommunication: '2026-09-18T09:40:00Z',
    snmpCommunity: 'public',
    firmwareVersion: 'CXTLS.081.234',
    supplies: [
      {
        type: 'TONER_BLACK',
        label: 'Toner Preto 24B6888',
        percent: 88,
        status: 'NORMAL',
        estimatedPagesRemaining: 17600,
        model: '24B6888',
        colorCode: '#1e293b',
      },
      {
        type: 'TONER_CYAN',
        label: 'Toner Ciano 24B6885',
        percent: 92,
        status: 'NORMAL',
        estimatedPagesRemaining: 11000,
        model: '24B6885',
        colorCode: '#0ea5e9',
      },
      {
        type: 'TONER_MAGENTA',
        label: 'Toner Magenta 24B6886',
        percent: 90,
        status: 'NORMAL',
        estimatedPagesRemaining: 10800,
        model: '24B6886',
        colorCode: '#ec4899',
      },
      {
        type: 'TONER_YELLOW',
        label: 'Toner Amarelo 24B6887',
        percent: 85,
        status: 'NORMAL',
        estimatedPagesRemaining: 10200,
        model: '24B6887',
        colorCode: '#eab308',
      },
    ],
    lastCounters: {
      total: 345000,
      mono: 250000,
      color: 95000,
      prints: 300000,
      copies: 45000,
      scans: 62000,
      readAt: '2026-09-18T09:40:00Z',
    },
  },
  {
    id: 'prt-5',
    code: 'PRT-HSC-003',
    serialNumber: 'U64831G9N1',
    assetTag: 'PAT-00910',
    manufacturer: 'Brother',
    model: 'DCP-L5652DN',
    ipAddress: '192.168.20.12',
    macAddress: '30:05:5C:A4:91:02',
    hostname: 'BROTHER-SANTOS-REC',
    location: 'Unidade Ambulatório Santos - Recepção',
    clientId: 'cli-1',
    branchId: 'br-1-2',
    departmentId: 'dep-1-1',
    contractId: 'ctr-1',
    type: 'MULTIFUNCIONAL',
    technology: 'LASER',
    isColor: false,
    maxPaperSize: 'A4',
    connectionType: 'REDE',
    status: 'OFFLINE',
    isMonitored: true,
    installedAt: '2024-04-10T14:00:00Z',
    lastCommunication: '2026-09-17T18:30:00Z',
    snmpCommunity: 'public',
    firmwareVersion: '1.24',
    supplies: [
      {
        type: 'TONER_BLACK',
        label: 'Toner TN-3472',
        percent: 18,
        status: 'BAIXO',
        estimatedPagesRemaining: 1400,
        model: 'TN-3472',
        colorCode: '#1e293b',
      },
      {
        type: 'DRUM',
        label: 'Cilindro DR-3440',
        percent: 42,
        status: 'NORMAL',
        estimatedPagesRemaining: 21000,
        model: 'DR-3440',
        colorCode: '#64748b',
      },
    ],
    lastCounters: {
      total: 54120,
      mono: 54120,
      color: 0,
      prints: 48900,
      copies: 5220,
      scans: 11000,
      readAt: '2026-09-17T18:30:00Z',
    },
  },
];

export const INITIAL_METERS: MeterReading[] = [
  {
    id: 'met-1',
    printerId: 'prt-1',
    printerSerial: 'CNB1N8G202',
    printerModel: 'HP LaserJet M528dn',
    clientName: 'Hospital Santa Catarina',
    timestamp: '2026-09-18T10:15:00Z',
    counterTotal: 148920,
    counterMono: 148920,
    counterColor: 0,
    counterPrints: 112400,
    counterCopies: 36520,
    counterScans: 41200,
    productionTotal: 2840,
    productionMono: 2840,
    productionColor: 0,
    source: 'AGENT',
    agentId: 'AGT-HSC-01',
    validationStatus: 'NORMAL',
  },
  {
    id: 'met-2',
    printerId: 'prt-2',
    printerSerial: 'QSK2A99120',
    printerModel: 'Kyocera ECOSYS M3655idn',
    clientName: 'Hospital Santa Catarina',
    timestamp: '2026-09-18T10:20:00Z',
    counterTotal: 89450,
    counterMono: 89450,
    counterColor: 0,
    counterPrints: 71200,
    counterCopies: 18250,
    counterScans: 19400,
    productionTotal: 1920,
    productionMono: 1920,
    productionColor: 0,
    source: 'AGENT',
    agentId: 'AGT-HSC-01',
    validationStatus: 'NORMAL',
  },
  {
    id: 'met-3',
    printerId: 'prt-3',
    printerSerial: '7529486241',
    printerModel: 'Ricoh MP C3004ex',
    clientName: 'Construtora Alfa',
    timestamp: '2026-09-18T10:18:00Z',
    counterTotal: 210340,
    counterMono: 132100,
    counterColor: 78240,
    counterPrints: 175000,
    counterCopies: 35340,
    counterScans: 48900,
    productionTotal: 4110,
    productionMono: 2310,
    productionColor: 1800,
    source: 'SNMP',
    agentId: 'AGT-ALF-01',
    validationStatus: 'NORMAL',
  },
  {
    id: 'met-4',
    printerId: 'prt-4',
    printerSerial: '7463554101',
    printerModel: 'Lexmark XC4140',
    clientName: 'Grupo Educacional Sigma',
    timestamp: '2026-09-18T09:40:00Z',
    counterTotal: 345000,
    counterMono: 250000,
    counterColor: 95000,
    counterPrints: 300000,
    counterCopies: 45000,
    counterScans: 62000,
    productionTotal: 12400,
    productionMono: 9200,
    productionColor: 3200,
    source: 'AGENT',
    agentId: 'AGT-SIG-01',
    validationStatus: 'NORMAL',
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-1',
    sku: 'TON-CF289A',
    description: 'Cartucho de Toner HP CF289A Preto (5.000 pág)',
    manufacturer: 'HP',
    compatibleModels: 'LaserJet Enterprise M507, M528dn',
    category: 'TONER',
    unit: 'UN',
    currentQuantity: 18,
    minQuantity: 8,
    maxQuantity: 40,
    location: 'Almoxarifado Central - Prateleira A1',
    unitCost: 285.5,
    supplier: 'Distribuidora Print Tech Brasil',
  },
  {
    id: 'inv-2',
    sku: 'TON-TK3182',
    description: 'Toner Kyocera TK-3182 Preto (21.000 pág)',
    manufacturer: 'Kyocera',
    compatibleModels: 'ECOSYS M3655idn, P3055dn',
    category: 'TONER',
    unit: 'UN',
    currentQuantity: 3, // abaixo do mínimo!
    minQuantity: 6,
    maxQuantity: 25,
    location: 'Almoxarifado Central - Prateleira B2',
    unitCost: 340.0,
    supplier: 'Kyocera Document Solutions Brasil',
  },
  {
    id: 'inv-3',
    sku: 'TON-RIC-MPC3503-MAG',
    description: 'Toner Ricoh MP C3503 Magenta (18.000 pág)',
    manufacturer: 'Ricoh',
    compatibleModels: 'Ricoh MP C3003, C3503, C3004ex, C3504',
    category: 'TONER',
    unit: 'UN',
    currentQuantity: 4,
    minQuantity: 4,
    maxQuantity: 15,
    location: 'Almoxarifado Central - Prateleira C3',
    unitCost: 410.0,
    supplier: 'Ricoh Latin America',
  },
  {
    id: 'inv-4',
    sku: 'DRM-DK3192',
    description: 'Unidade de Cilindro Kyocera DK-3192 (500.000 pág)',
    manufacturer: 'Kyocera',
    compatibleModels: 'M3655idn, M3145idn',
    category: 'CILINDRO',
    unit: 'UN',
    currentQuantity: 5,
    minQuantity: 2,
    maxQuantity: 10,
    location: 'Almoxarifado Central - Armário Seguro',
    unitCost: 890.0,
    supplier: 'Kyocera Document Solutions Brasil',
  },
  {
    id: 'inv-5',
    sku: 'FUS-RM22005',
    description: 'Unidade Fusora HP 110V RM2-2005-000',
    manufacturer: 'HP',
    compatibleModels: 'M507, M528',
    category: 'FUSOR',
    unit: 'UN',
    currentQuantity: 2,
    minQuantity: 2,
    maxQuantity: 6,
    location: 'Almoxarifado Central - Peças Críticas',
    unitCost: 1120.0,
    supplier: 'Distribuidora Print Tech Brasil',
  },
];

export const INITIAL_MOVEMENTS: InventoryMovement[] = [
  {
    id: 'mov-1',
    itemId: 'inv-1',
    itemDescription: 'Cartucho de Toner HP CF289A Preto',
    type: 'ENTRADA',
    quantity: 20,
    previousQuantity: 2,
    newQuantity: 22,
    reason: 'Compra programada NF-e 45892',
    timestamp: '2026-09-10T14:00:00Z',
    registeredBy: 'Juliana Mendes (Estoque)',
  },
  {
    id: 'mov-2',
    itemId: 'inv-1',
    itemDescription: 'Cartucho de Toner HP CF289A Preto',
    type: 'SAIDA',
    quantity: 4,
    previousQuantity: 22,
    newQuantity: 18,
    reason: 'Abastecimento maleta técnica OS-2026-0012',
    technicianName: 'Rodrigo Santos',
    timestamp: '2026-09-14T09:15:00Z',
    registeredBy: 'Rodrigo Santos',
  },
];

export const INITIAL_ALERTS: AlertEvent[] = [
  {
    id: 'alt-1',
    type: 'TONER_CRITICO',
    severity: 'CRITICA',
    status: 'ABERTO',
    title: 'Toner Preto em Nível Crítico (8%)',
    description: 'Kyocera M3655idn (Farmácia Central) atingiu 8% de toner. Restam aprox. 420 páginas.',
    entityType: 'PRINTER',
    entityId: 'prt-2',
    entityName: 'PRT-HSC-002 (Kyocera M3655idn)',
    clientId: 'cli-1',
    clientName: 'Hospital Santa Catarina',
    createdAt: '2026-09-18T08:30:00Z',
  },
  {
    id: 'alt-2',
    type: 'IMPRESSORA_OFFLINE',
    severity: 'ALTA',
    status: 'ABERTO',
    title: 'Impressora Sem Comunicação SNMP',
    description: 'Brother DCP-L5652DN (Recepção Santos) não responde a pings SNMP há mais de 16 horas.',
    entityType: 'PRINTER',
    entityId: 'prt-5',
    entityName: 'PRT-HSC-003 (Brother DCP-L5652DN)',
    clientId: 'cli-1',
    clientName: 'Hospital Santa Catarina',
    createdAt: '2026-09-18T06:00:00Z',
  },
  {
    id: 'alt-3',
    type: 'ESTOQUE_BAIXO',
    severity: 'ALTA',
    status: 'RECONHECIDO',
    title: 'Estoque Mínimo Violado: Toner TK-3182',
    description: 'Quantidade atual (3 un) está abaixo do estoque de segurança configurado (6 un).',
    entityType: 'INVENTORY',
    entityId: 'inv-2',
    entityName: 'Toner Kyocera TK-3182',
    createdAt: '2026-09-17T16:00:00Z',
  },
  {
    id: 'alt-4',
    type: 'CONTRATO_VENCENDO',
    severity: 'MEDIA',
    status: 'EM_ANALISE',
    title: 'Contrato Próximo da Renovação Anual',
    description: 'Contrato CTR-2024-001 vencerá em 45 dias. Iniciar negociação de aditivo e reajuste IGPM.',
    entityType: 'CONTRACT',
    entityId: 'ctr-1',
    entityName: 'CTR-2024-001 (Hospital Santa Catarina)',
    clientId: 'cli-1',
    clientName: 'Hospital Santa Catarina',
    createdAt: '2026-09-15T09:00:00Z',
  },
];

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: 'tkt-1',
    code: 'CH-2026-0042',
    clientId: 'cli-1',
    clientName: 'Hospital Santa Catarina',
    branchId: 'br-1-1',
    branchName: 'Sede Bela Vista',
    departmentId: 'dep-1-3',
    departmentName: 'Farmácia Central',
    printerId: 'prt-2',
    printerModel: 'Kyocera ECOSYS M3655idn',
    printerSerial: 'QSK2A99120',
    requesterName: 'Dra. Camila Nogueira',
    requesterEmail: 'camila.farmacia@hospitalsantacatarina.com.br',
    category: 'SUPRIMENTO',
    subcategory: 'Substituição de Toner Urgente',
    priority: 'CRITICA',
    description: 'A impressora exibe mensagem "Toner baixo - Substituir em breve". Farmácia não pode parar a impressão de prescrições.',
    status: 'EM_ATENDIMENTO',
    assignedTechnicianId: 'tec-1',
    assignedTechnicianName: 'Rodrigo Santos',
    slaHours: 4,
    slaDeadline: '2026-09-18T12:30:00Z',
    openedAt: '2026-09-18T08:30:00Z',
    attendedAt: '2026-09-18T09:00:00Z',
    origin: 'MONITORAMENTO',
  },
  {
    id: 'tkt-2',
    code: 'CH-2026-0041',
    clientId: 'cli-2',
    clientName: 'Construtora Alfa',
    branchId: 'br-2-1',
    branchName: 'Matriz Vila Olímpia',
    departmentId: 'dep-2-1',
    departmentName: 'Engenharia & Projetos CAD',
    printerId: 'prt-3',
    printerModel: 'Ricoh MP C3004ex A3 Color',
    printerSerial: '7529486241',
    requesterName: 'Lucas Ferraz',
    requesterEmail: 'lucas.cad@alfaengenharia.com.br',
    category: 'QUALIDADE_IMPRESSAO',
    subcategory: 'Faixas magenta nas impressões de planta',
    priority: 'NORMAL',
    description: 'Ao plotar projetos coloridos em formato A3 surgiram riscos magenta horizontais contínuos.',
    status: 'TRIAGEM',
    slaHours: 24,
    slaDeadline: '2026-09-19T10:00:00Z',
    openedAt: '2026-09-18T10:00:00Z',
    origin: 'CLIENTE',
  },
  {
    id: 'tkt-3',
    code: 'CH-2026-0040',
    clientId: 'cli-1',
    clientName: 'Hospital Santa Catarina',
    branchId: 'br-1-2',
    branchName: 'Unidade Ambulatório Santos',
    departmentId: 'dep-1-1',
    departmentName: 'Recepção',
    printerId: 'prt-5',
    printerModel: 'Brother DCP-L5652DN',
    printerSerial: 'U64831G9N1',
    requesterName: 'Renata Lins',
    requesterEmail: 'renata.santos@hospitalsantacatarina.com.br',
    category: 'REDE_CONECTIVIDADE',
    subcategory: 'Equipamento não responde a ping',
    priority: 'ALTA',
    description: 'Equipamento desconectou da rede local após oscilação elétrica. Necessário reiniciar interface ou reprogramar IP estático.',
    status: 'AGENDADO',
    assignedTechnicianId: 'tec-2',
    assignedTechnicianName: 'Bruno Henrique',
    slaHours: 8,
    slaDeadline: '2026-09-18T17:00:00Z',
    openedAt: '2026-09-18T07:15:00Z',
    attendedAt: '2026-09-18T08:00:00Z',
    origin: 'SISTEMA',
  },
];

export const INITIAL_SERVICE_ORDERS: ServiceOrder[] = [
  {
    id: 'os-1',
    code: 'OS-2026-0019',
    ticketId: 'tkt-1',
    ticketCode: 'CH-2026-0042',
    clientId: 'cli-1',
    clientName: 'Hospital Santa Catarina',
    branchName: 'Sede Bela Vista - Farmácia Central',
    address: 'Av. Paulista, 200 - 1º Andar',
    printerId: 'prt-2',
    printerModel: 'Kyocera ECOSYS M3655idn',
    printerSerial: 'QSK2A99120',
    technicianId: 'tec-1',
    technicianName: 'Rodrigo Santos',
    priority: 'CRITICA',
    status: 'EM_EXECUCAO',
    scheduledDate: '2026-09-18',
    serviceDescription: 'Substituição preventiva de cartucho toner TK-3182 e limpeza do trajeto óptico.',
    diagnosis: 'Toner atingiu 8% de nível residual.',
    partsReplaced: [
      {
        itemId: 'inv-2',
        description: 'Toner Kyocera TK-3182 Preto',
        quantity: 1,
      },
    ],
    checklist: [
      { task: 'Limpeza do vidro de exposição e espelhos', done: true },
      { task: 'Verificação e aspiração de resíduos no trajeto de papel', done: true },
      { task: 'Instalação do novo toner original TK-3182', done: true },
      { task: 'Verificação do cilindro e unidade reveladora', done: false },
      { task: 'Emissão de página de teste e relatório de status', done: false },
    ],
    countersAtService: {
      total: 89450,
      mono: 89450,
      color: 0,
    },
    startedAt: '2026-09-18T09:15:00Z',
  },
  {
    id: 'os-2',
    code: 'OS-2026-0018',
    ticketId: 'tkt-3',
    ticketCode: 'CH-2026-0040',
    clientId: 'cli-1',
    clientName: 'Hospital Santa Catarina',
    branchName: 'Unidade Ambulatório Santos',
    address: 'Av. Ana Costa, 150 - Recepção',
    printerId: 'prt-5',
    printerModel: 'Brother DCP-L5652DN',
    printerSerial: 'U64831G9N1',
    technicianId: 'tec-2',
    technicianName: 'Bruno Henrique',
    priority: 'ALTA',
    status: 'EM_DESLOCAMENTO',
    scheduledDate: '2026-09-18',
    serviceDescription: 'Diagnóstico de conectividade em rede e reconfiguração de IP estático 192.168.20.12.',
    partsReplaced: [],
    checklist: [
      { task: 'Teste de cabo de rede RJ45 e porta do switch', done: false },
      { task: 'Reset de placa de rede e reatribuição de IP', done: false },
      { task: 'Teste de ping SNMP pelo Agente PrintControl', done: false },
      { task: 'Impressão de teste a partir de 2 estações de atendimento', done: false },
    ],
    startedAt: '2026-09-18T09:45:00Z',
  },
];

export const INITIAL_TECHNICIANS: Technician[] = [
  {
    id: 'tec-1',
    name: 'Rodrigo Santos',
    registrationNumber: 'TEC-0089',
    cpf: '342.119.888-02',
    phone: '(11) 98765-4321',
    email: 'rodrigo.tec@santaprint.com.br',
    specialty: 'Especialista Kyocera & HP Multifuncionais Laser',
    coverageCities: ['São Paulo', 'Guarulhos', 'Osasco'],
    status: 'EM_ATENDIMENTO',
    currentLatitude: -23.5658,
    currentLongitude: -46.6515,
  },
  {
    id: 'tec-2',
    name: 'Bruno Henrique',
    registrationNumber: 'TEC-0094',
    cpf: '221.908.444-19',
    phone: '(13) 99123-8877',
    email: 'bruno.tec@santaprint.com.br',
    specialty: 'Especialista Ricoh & Lexmark Color A3/A4',
    coverageCities: ['Santos', 'São Vicente', 'Praia Grande', 'Cubatão'],
    status: 'EM_ROTA',
    currentLatitude: -23.9554,
    currentLongitude: -46.3312,
  },
  {
    id: 'tec-3',
    name: 'Leandro Vasconcelos',
    registrationNumber: 'TEC-0102',
    cpf: '401.765.221-50',
    phone: '(19) 98112-9900',
    email: 'leandro.tec@santaprint.com.br',
    specialty: 'Especialista em Redes, SNMP e Agentes de Bilhetagem',
    coverageCities: ['Campinas', 'Americana', 'Indaiatuba', 'Jundiaí'],
    status: 'DISPONIVEL',
    currentLatitude: -22.8945,
    currentLongitude: -47.0583,
  },
];

export const INITIAL_ROUTES: RouteStop[] = [
  {
    id: 'rt-1',
    technicianId: 'tec-1',
    osId: 'os-1',
    osCode: 'OS-2026-0019',
    clientId: 'cli-1',
    clientName: 'Hospital Santa Catarina (Bela Vista)',
    address: 'Av. Paulista, 200',
    city: 'São Paulo',
    orderIndex: 1,
    scheduledTime: '09:00',
    estimatedMinutes: 45,
    priority: 'CRITICA',
    status: 'EM_ANDAMENTO',
    latitude: -23.5658,
    longitude: -46.6515,
  },
  {
    id: 'rt-2',
    technicianId: 'tec-1',
    osId: 'os-pending-1',
    osCode: 'OS-2026-0020',
    clientId: 'cli-2',
    clientName: 'Construtora Alfa (Vila Olímpia)',
    address: 'Rua Funchal, 418',
    city: 'São Paulo',
    orderIndex: 2,
    scheduledTime: '11:15',
    estimatedMinutes: 60,
    priority: 'NORMAL',
    status: 'PENDENTE',
    latitude: -23.5934,
    longitude: -46.6853,
  },
  {
    id: 'rt-3',
    technicianId: 'tec-2',
    osId: 'os-2',
    osCode: 'OS-2026-0018',
    clientId: 'cli-1',
    clientName: 'Hospital Santa Catarina (Santos)',
    address: 'Av. Ana Costa, 150',
    city: 'Santos',
    orderIndex: 1,
    scheduledTime: '10:30',
    estimatedMinutes: 50,
    priority: 'ALTA',
    status: 'PENDENTE',
    latitude: -23.9554,
    longitude: -46.3312,
  },
];

export const INITIAL_CONTRACTS: Contract[] = [
  {
    id: 'ctr-1',
    code: 'CTR-2024-001',
    clientId: 'cli-1',
    clientName: 'Hospital Santa Catarina S/A',
    type: 'FRANQUIA',
    status: 'ATIVO',
    startDate: '2024-03-01',
    endDate: '2026-10-31',
    billingDay: 25,
    monthlyFixedFee: 4850.0,
    franchiseMonoPages: 40000,
    franchiseColorPages: 0,
    costPerMonoSurplus: 0.045, // R$ 0,045 por pág excedente
    costPerColorSurplus: 0.0,
    costMinimum: 4850.0,
    slaResponseHours: 4,
    printerIds: ['prt-1', 'prt-2', 'prt-5'],
    notes: 'Contrato de missão crítica hospitalar com substituição em até 4h.',
  },
  {
    id: 'ctr-2',
    code: 'CTR-2024-012',
    clientId: 'cli-2',
    clientName: 'Alfa Engenharia e Construções Ltda',
    type: 'HÍBRIDO',
    status: 'ATIVO',
    startDate: '2024-06-01',
    endDate: '2027-05-31',
    billingDay: 20,
    monthlyFixedFee: 2900.0,
    franchiseMonoPages: 10000,
    franchiseColorPages: 3000,
    costPerMonoSurplus: 0.05,
    costPerColorSurplus: 0.28,
    costMinimum: 2900.0,
    slaResponseHours: 8,
    printerIds: ['prt-3'],
    notes: 'Franquia compartilhada com tarifação diferenciada para grandes formatos A3.',
  },
  {
    id: 'ctr-3',
    code: 'CTR-2024-025',
    clientId: 'cli-3',
    clientName: 'Colégio e Faculdade Sigma Brasil Ltda',
    type: 'BILHETAGEM',
    status: 'ATIVO',
    startDate: '2024-08-01',
    endDate: '2026-12-31',
    billingDay: 28,
    monthlyFixedFee: 1500.0,
    franchiseMonoPages: 25000,
    franchiseColorPages: 5000,
    costPerMonoSurplus: 0.038,
    costPerColorSurplus: 0.22,
    costMinimum: 1500.0,
    slaResponseHours: 8,
    printerIds: ['prt-4'],
    notes: 'Tarifação por página pura com locação mínima de infraestrutura.',
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-fat-1',
    code: 'FAT-2026-08-001',
    contractId: 'ctr-1',
    contractCode: 'CTR-2024-001',
    clientId: 'cli-1',
    clientName: 'Hospital Santa Catarina S/A',
    periodMonth: '2026-08',
    periodLabel: 'Agosto/2026',
    monoProduction: 48200,
    colorProduction: 0,
    monoFranchise: 40000,
    colorFranchise: 0,
    monoSurplus: 8200,
    colorSurplus: 0,
    monthlyFixedFee: 4850.0,
    monoSurplusTotal: 369.0,
    colorSurplusTotal: 0.0,
    adjustments: 0.0,
    totalAmount: 5219.0,
    dueDate: '2026-09-25',
    status: 'PAGA',
    generatedAt: '2026-09-01T08:00:00Z',
    isFrozen: true,
  },
  {
    id: 'inv-fat-2',
    code: 'FAT-2026-08-002',
    contractId: 'ctr-2',
    contractCode: 'CTR-2024-012',
    clientId: 'cli-2',
    clientName: 'Alfa Engenharia e Construções Ltda',
    periodMonth: '2026-08',
    periodLabel: 'Agosto/2026',
    monoProduction: 11400,
    colorProduction: 3850,
    monoFranchise: 10000,
    colorFranchise: 3000,
    monoSurplus: 1400,
    colorSurplus: 850,
    monthlyFixedFee: 2900.0,
    monoSurplusTotal: 70.0,
    colorSurplusTotal: 238.0,
    adjustments: 0.0,
    totalAmount: 3208.0,
    dueDate: '2026-09-20',
    status: 'PAGA',
    generatedAt: '2026-09-01T08:00:00Z',
    isFrozen: true,
  },
  {
    id: 'inv-fat-3',
    code: 'FAT-2026-09-001',
    contractId: 'ctr-1',
    contractCode: 'CTR-2024-001',
    clientId: 'cli-1',
    clientName: 'Hospital Santa Catarina S/A',
    periodMonth: '2026-09',
    periodLabel: 'Setembro/2026 (Parcial)',
    monoProduction: 44100,
    colorProduction: 0,
    monoFranchise: 40000,
    colorFranchise: 0,
    monoSurplus: 4100,
    colorSurplus: 0,
    monthlyFixedFee: 4850.0,
    monoSurplusTotal: 184.5,
    colorSurplusTotal: 0.0,
    adjustments: 0.0,
    totalAmount: 5034.5,
    dueDate: '2026-10-25',
    status: 'EM_CONFERENCIA',
    generatedAt: '2026-09-18T00:00:00Z',
    isFrozen: false,
  },
];

export const INITIAL_AGENTS: AgentDevice[] = [
  {
    id: 'agt-1',
    agentId: 'AGT-HSC-01',
    hostname: 'SRV-PRINT-HSC',
    ipAddress: '192.168.10.10',
    version: 'v2.4.1',
    osVersion: 'Windows Server 2022 Datacenter',
    status: 'ONLINE',
    lastHeartbeat: '2026-09-18T10:28:10Z',
    monitoredPrinterCount: 3,
    lastCollectionTime: '2026-09-18T10:20:00Z',
    pendingQueueCount: 0,
  },
  {
    id: 'agt-2',
    agentId: 'AGT-ALF-01',
    hostname: 'SRV-FILE-ALFA',
    ipAddress: '10.0.50.15',
    version: 'v2.4.1',
    osVersion: 'Windows Server 2019 Standard',
    status: 'ONLINE',
    lastHeartbeat: '2026-09-18T10:27:45Z',
    monitoredPrinterCount: 1,
    lastCollectionTime: '2026-09-18T10:18:00Z',
    pendingQueueCount: 0,
  },
  {
    id: 'agt-3',
    agentId: 'AGT-SIG-01',
    hostname: 'SRV-SIGMA-CAMP',
    ipAddress: '172.16.2.5',
    version: 'v2.3.9',
    osVersion: 'Windows 11 Pro Enterprise',
    status: 'ONLINE',
    lastHeartbeat: '2026-09-18T10:25:00Z',
    monitoredPrinterCount: 1,
    lastCollectionTime: '2026-09-18T09:40:00Z',
    pendingQueueCount: 0,
  },
];

export const INITIAL_ORACLE_LOGS: OracleSyncLog[] = [
  {
    id: 'orc-1',
    timestamp: '2026-09-18T06:00:00Z',
    entity: 'CLIENTES',
    recordsCount: 3,
    status: 'SINCRONIZADO',
    durationMs: 420,
    details: 'Validação de cadastros fiscais e limites de crédito contra Oracle ERP 19c.',
  },
  {
    id: 'orc-2',
    timestamp: '2026-09-18T06:01:10Z',
    entity: 'FATURAMENTO',
    recordsCount: 2,
    status: 'SINCRONIZADO',
    durationMs: 650,
    details: 'Exportação de títulos a receber das faturas FAT-2026-08-001 e 002.',
  },
  {
    id: 'orc-3',
    timestamp: '2026-09-18T06:02:00Z',
    entity: 'EQUIPAMENTOS',
    recordsCount: 5,
    status: 'SINCRONIZADO',
    durationMs: 380,
    details: 'Atualização de patrimônio e depreciação no módulo Ativo Fixo.',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-1',
    timestamp: '2026-09-18T09:15:00Z',
    userName: 'Rodrigo Santos',
    userRole: 'TECNICO',
    action: 'UPDATE',
    entity: 'SERVICE_ORDER',
    entityId: 'os-1',
    details: 'Iniciou atendimento da OS-2026-0019 (Kyocera M3655idn Farmácia).',
    ipAddress: '189.44.12.98',
  },
  {
    id: 'aud-2',
    timestamp: '2026-09-18T08:30:00Z',
    userName: 'PrintControl Agent Daemon',
    userRole: 'ADMIN',
    action: 'CREATE',
    entity: 'TICKET',
    entityId: 'tkt-1',
    details: 'Abertura automática de chamado CH-2026-0042 por alerta de toner 8%.',
    ipAddress: '192.168.10.10',
  },
  {
    id: 'aud-3',
    timestamp: '2026-09-01T08:00:00Z',
    userName: 'Juliana Mendes',
    userRole: 'FATURAMENTO',
    action: 'APPROVE',
    entity: 'BILLING_CLOSING',
    entityId: 'FAT-2026-08',
    details: 'Congelamento e homologação do fechamento de bilhetagem de Agosto/2026.',
    ipAddress: '177.38.190.22',
  },
];
